spring:
  profiles:
    active:
    - stage
---
spring:
  profiles: local
  application:
    name: awan-tunai-test
  datasource:
    url: jdbc:mysql://localhost:3306/hitarokkap-db
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    continue-on-error: true
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true    
server:
  context-path: /api
  port: 8061
logging:
  path: ./logs
  file: ${logging.path}/${spring.application.name}.log
  level:
   ROOT: ERROR
   hita.rokkap.com: INFO
   org.springframework.web: INFO
---
spring:
  profiles: stage
  application:
    name: hitarokkap
  datasource:
    url : jdbc:mysql://localhost:3306/hitarokkap-db?useSSL=false
    username: root
    password: admin123
    driver-class-name: com.mysql.jdbc.Driver
    continue-on-error: true
  jpa:
    show-sql: false
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
    generate-ddl: true    
server:
  context-path: /api
  port: 8061
logging:
  path: ./logs
  file: ${logging.path}/${spring.application.name}.log
  level:
   ROOT: ERROR
   awantunai.test: INFO
#   org.springframework.web: DEBUG